terms:
    - id: http://rightsstatements.org/vocab/InC/1.0/
      term: In Copyright
      active: true
    - id: https://creativecommons.org/licenses/by/4.0/
      term: Creative Commons BY Attribution 4.0 International
      active: true
    - id: https://creativecommons.org/licenses/by-sa/4.0/
      term: Creative Commons BY-SA Attribution-ShareAlike 4.0 International
      active: true
    - id: https://creativecommons.org/licenses/by-nd/4.0/
      term: Creative Commons BY-ND Attribution-NoDerivatives 4.0 International
      active: true
    - id: https://creativecommons.org/licenses/by-nc/4.0/
      term: Creative Commons BY-NC Attribution-NonCommercial 4.0 International
      active: true
    - id: https://creativecommons.org/licenses/by-nc-nd/4.0/
      term: Creative Commons BY-NC-ND Attribution-NonCommercial-NoDerivs 4.0 International
      active: true
    - id: https://creativecommons.org/licenses/by-nc-sa/4.0/
      term: Creative Commons BY-NC-SA Attribution-NonCommercial-ShareAlike 4.0 International
      active: true
    - id: http://creativecommons.org/publicdomain/zero/1.0/
      term: Creative Commons CC0 1.0 Universal
      active: true
    - id: http://creativecommons.org/publicdomain/mark/1.0/
      term: Creative Commons Public Domain Mark 1.0
      active: true
    - id: http://www.apache.org/licenses/LICENSE-2.0
      term: Apache License 2.0
      active: true
    - id: http://www.gnu.org/licenses/gpl.html
      term: GNU General Public License
      active: true
    - id: http://opensource.org/licenses/MIT
      term: MIT License
      active: true
    - id: http://creativecommons.org/licenses/by-nc-nd/2.1/jp/
      term: Creative Commons BY-NC-ND 2.1 JP
      active: false
    - id: http://creativecommons.org/licenses/by-nc-nd/3.0/
      term: Creative Commons BY-NC-ND 3.0
      active: false
    - id: http://creativecommons.org/licenses/by-nc-sa/2.1/jp/
      term: Creative Commons BY-NC-SA 2.1 JP
      active: false
    - id: http://creativecommons.org/licenses/by-nc/3.0/
      term: Creative Commons BY-NC 3.0
      active: false
    - id: http://creativecommons.org/licenses/by-nd/2.1/jp/
      term: Creative Commons BY-ND 2.1 JP
      active: false
    - id: http://creativecommons.org/licenses/by-nd/3.0/
      term: Creative Commons BY-ND 3.0
      active: false
    - id: http://creativecommons.org/licenses/by-sa/3.0/
      term: Creative Commons BY-SA 3.0
      active: false
    - id: http://creativecommons.org/licenses/by/2.0/de/
      term: Creative Commons BY 2.0 DE
      active: false
    - id: http://creativecommons.org/licenses/by/2.1/jp/
      term: Creative Commons BY 2.1 JP
      active: false
    - id: http://creativecommons.org/licenses/by/3.0/
      term: Creative Commons BY 3.0
      active: false
    - id: http://creativecommons.org/licenses/by/3.0/de/
      term: Creative Commons BY 3.0 DE
      active: false
