#
# You can manually fill in these values or use the ENV variables.
#
analytics:
  google:
    analytics_id: <%= ENV['GOOGLE_ANALYTICS_ID'] %>
    app_name: <%= ENV['GA_APP_NAME'] %>
    app_version: <%= ENV['GA_APP_VERSION'] %>
    privkey_path: <%= ENV['GA_PRIVATE_KEY_PATH'] %>
    privkey_secret: <%= ENV['GA_PRIVATE_KEY_SECRET'] %>
    client_email: <%= ENV['GA_CLIENT_EMAIL'] %>
  matomo:
    base_url: <%= ENV['MATOMO_BASE_URL'] %>
    site_id: <%= ENV['MATOMO_SITE_ID'] %>
    auth_token: <%= ENV['MATOMO_AUTH_TOKEN'] %>